// ================================================
// FILE: src/controllers/reportController.js
// ================================================
const PDFDocument = require('pdfkit');
const { all, get } = require('../utils/helper');
const { logAction } = require('../utils/auditLogger');

const generateMasterReport = async (req, res) => {
    try {
        // 1. Fetch all necessary data
        const totalGuards = await get("SELECT COUNT(*) as count FROM applicants WHERE status = 'Hired'");
        const pendingApps = await get("SELECT COUNT(*) as count FROM applicants WHERE status = 'Pending'");
        const activeDeployments = await get("SELECT COUNT(*) as count FROM deployments WHERE status = 'Active'");
        
        // Fetch Branches with their current active deployment counts
        const branches = await all(`
            SELECT b.name, b.location, b.required_guards, 
                   (SELECT COUNT(*) FROM deployments d WHERE d.branch_id = b.id AND d.status = 'Active') as active_count
            FROM branches b
            ORDER BY b.name ASC
        `);

        // 2. Initialize PDF Document
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=Aloha_Master_Report_${new Date().toISOString().slice(0,10)}.pdf`);
        doc.pipe(res);

        // 3. Header Section
        doc.font('Helvetica-Bold').fontSize(24).fillColor('#e53828').text('ALOHA SECURITY AGENCY', { align: 'center' });
        doc.font('Helvetica').fontSize(12).fillColor('#475569').text('Executive System Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(10).fillColor('#94a3b8').text(`Generated by: Admin #${req.user.id}`, { align: 'right' });
        doc.text(`Date: ${new Date().toLocaleString()}`, { align: 'right' });
        doc.moveDown(2);

        // 4. KPI Summary Section
        doc.font('Helvetica-Bold').fontSize(14).fillColor('#0f172a').text('Operational Overview');
        doc.moveTo(50, doc.y + 5).lineTo(545, doc.y + 5).strokeColor('#e2e8f0').stroke();
        doc.moveDown(1.5);

        doc.font('Helvetica').fontSize(11).fillColor('#334155');
        doc.text(`Total Cleared Guards (Active Roster): `, 50, doc.y, { continued: true }).font('Helvetica-Bold').text(`${totalGuards.count}`);
        doc.font('Helvetica').text(`Active Deployments (On Duty): `, 50, doc.y + 10, { continued: true }).font('Helvetica-Bold').text(`${activeDeployments.count}`);
        doc.font('Helvetica').text(`Pending Applications (Needs Review): `, 50, doc.y + 10, { continued: true }).font('Helvetica-Bold').text(`${pendingApps.count}`);
        doc.moveDown(3);

        // 5. Branch Status Table
        doc.font('Helvetica-Bold').fontSize(14).fillColor('#0f172a').text('Facility Deployment Status');
        doc.moveTo(50, doc.y + 5).lineTo(545, doc.y + 5).strokeColor('#e2e8f0').stroke();
        doc.moveDown(1.5);

        // Table Headers
        const tableTop = doc.y;
        const col1 = 50;  // Branch Name
        const col2 = 250; // Location
        const col3 = 430; // Staffing
        
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#64748b');
        doc.text('BRANCH NAME', col1, tableTop);
        doc.text('LOCATION', col2, tableTop);
        doc.text('STAFFING', col3, tableTop);
        
        doc.moveTo(50, tableTop + 15).lineTo(545, tableTop + 15).strokeColor('#cbd5e1').stroke();
        
        let y = tableTop + 25;
        doc.font('Helvetica').fillColor('#334155');

        branches.forEach(b => {
            if (y > 750) {
                doc.addPage();
                y = 50;
            }

            const staffingText = `${b.active_count} / ${b.required_guards} Guards`;
            const isCritical = b.active_count < b.required_guards;

            doc.fillColor('#0f172a').text(b.name, col1, y, { width: 180 });
            doc.fillColor('#64748b').text(b.location, col2, y, { width: 160 });
            
            if (isCritical) {
                doc.fillColor('#e53828').font('Helvetica-Bold').text(staffingText + ' (CRITICAL)', col3, y);
            } else {
                doc.fillColor('#10b981').font('Helvetica').text(staffingText + ' (SECURED)', col3, y);
            }
            
            y += 25;
        });

        // 6. Finalize
        await logAction(req, 'REPORT_GEN', `Admin generated Master Dashboard Report PDF.`);
        doc.end();

    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false, data: "Failed to generate PDF report." });
    }
};

module.exports = { generateMasterReport };